### ISSUE TITLE
Is there any need of notice if toolchains' tools are used for building binaries without copying its sources?

### ISSUE THREAD

**Issue by lakshayrohila** [dimkr/toolchains#10]
Thanks @dimkr for this wonderful tool!

My question:

As written in the [COPYING](https://github.com/dimkr/toolchains/blob/master/COPYING),
https://github.com/dimkr/toolchains/blob/0343642aa1b72bebca006a84e565d37ad8486e3e/COPYING#L10-L11

So, when I use the tools (`...-gcc`  and other stuff) provided by `toolchains` for compiling my program without copying any parts of source code, do I still need to put the notice?

If so, which file can I create (`NOTICE.md` maybe, or something else)?

Thanks.

**Comment by dimkr** [comment]
As far as I understand, you don't need to put this notice because this repository only contains build configurations and the infrastructure used to build the toolchains. The contents of this repository don't go into your binaries.

You **will** need to comply with the license terms of things that go into the binaries built by the toolchain, though - for example, GCC (because you're linking against a static libgcc), musl, etc'.
